name: Release Build
on:
  release:
    types: [created]
jobs:
  publish:
    if: startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD

      - id: install-gpg
        name: Install GPG Secret Key
        env:
          SECRET_KEY_BASE64: ${{ secrets.OSSRH_GPG_SECRET_KEY_BASE64 }}
        run: |
          echo $SECRET_KEY_BASE64 | base64 --decode | gpg --batch --import

      - id: set-release-version
        name: Set Relese Version
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          VERSION=$(echo $TAG_NAME | cut -d 'v' -f 2)
          mvn --no-transfer-progress --batch-mode versions:set versions:commit -DnewVersion=$VERSION 

      - id: publish-to-central
        name: Publish to Central Repository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: |
          mvn --no-transfer-progress --batch-mode \
            clean deploy \
            -Dgpg.passphrase=$GPG_PASSWORD \
            -Dossrh.username=$OSSRH_USERNAME \
            -Dossrh.password=$OSSRH_PASSWORD \
            -P ossrh
